FROM python:3.7-slim

ENV PYTHONFAULTHANDLER=1 \
  PYTHONHASHSEED=random \
  PYTHONUNBUFFERED=1 \
  PIP_DEFAULT_TIMEOUT=100 \
  PIP_DISABLE_PIP_VERSION_CHECK=1 \
  PIP_NO_CACHE_DIR=1 

WORKDIR /barchart_import

ENV  POETRY_VERSION=1.0.5 

RUN pip install "poetry==$POETRY_VERSION"

COPY poetry.lock .
COPY pyproject.toml .
COPY barchart_import ./barchart_import

COPY fixtures ./fixtures

RUN poetry config virtualenvs.create false && \
    poetry install -v --no-interaction --no-ansi

COPY scripts/tests/run-tests.sh /barchart_import/run-tests.sh

COPY .flake8 .isort.cfg /barchart_import/

COPY scripts/tests/check-codequality.sh /barchart_import/check-codequality.sh

ENTRYPOINT ["/barchart_import/run-tests.sh"]